### ISSUE TITLE
Добавить возможность загружать картинки и получать их url

### ISSUE THREAD

**Issue by shalkov** [LastSprint/mocker#19]
Было бы здорово, если у мокера была функция, которая бы позволяла получить путь до картинги без авторизации и использовать этот URL в ответах мокера.

Например, у меня есть картинка, я её загружаю в мокер и она имеет адрес:
https://r2.mocker.site.ru/files/android/memes/mem1.jpg.

После, где-нибудь в ответах мокера, я бы использовал эту ссылку на картинку:
```{
  "url": "/site/v1/new/mobile-images",
  "method": "GET",
  "statusCode": 200,
  "response": {
    "android": {
      "name": "mem1",
      "url": "https://r2.mocker.site.ru/files/android/memes/mem1.jpg"
    }
  }
}```

**Comment by LastSprint** [comment]
Урл самим составлять надо будет - правила в доке описаны
